package frc.robot.subsystems.interfaces;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.units.measure.Angle;
import frc.robot.Constants;

public class Hood {
  private static final TalonFX mFollowerPivotMotor =
    new TalonFX(Constants.CAN_IDS.BACK_FLYWHEEL_MOTOR);
  private static final TalonFX mMasterPivotMotor =
    new TalonFX(Constants.CAN_IDS.FRONT_MASTER_FLYWHEEL_MOTOR);  
  public static final StatusSignal<Angle> mBackMotorVelo = mFollowerPivotMotor.getPosition();
  public static final StatusSignal<Angle> mFrontMotorVelo = mMasterPivotMotor.getPosition();

  private static class TurretState {
    private static double currentPositionDegrees = 0.0;
    private static double currentSwerveRotDeg = 0.0;
    private static double currentRadialVelocityMPS = 0.0;
    private static double currentTangentialOmega = 0.0; // angular velocity generated by the swerve movement
    private static double currentDistToTarget = 0.0; // this should only be used for estimating the TOF
  }
  
  private class SimulationObjects {
    private static double desiredTurretAngleFieldRel;
  }
  
  public static void init() {
      TalonFXConfiguration frontPivotConfig = new TalonFXConfiguration();
      frontPivotConfig.CurrentLimits.StatorCurrentLimitEnable = false;
      frontPivotConfig.CurrentLimits.SupplyCurrentLimit = 60;
      frontPivotConfig.CurrentLimits.SupplyCurrentLimitEnable = true;
      frontPivotConfig.CurrentLimits.SupplyCurrentLowerLimit = 40;
      frontPivotConfig.CurrentLimits.SupplyCurrentLowerTime = 0.5;
      frontPivotConfig.TorqueCurrent.PeakForwardTorqueCurrent = 100;
      frontPivotConfig.TorqueCurrent.PeakReverseTorqueCurrent = -100;
      frontPivotConfig.Slot0.kS = 0;
      frontPivotConfig.Slot0.kV = 0;
      frontPivotConfig.Slot0.kA = 0;
      frontPivotConfig.Slot0.kP = 0;
      frontPivotConfig.Slot0.kI = 0;
      frontPivotConfig.Slot0.kD = 0;
      frontPivotConfig.MotionMagic.MotionMagicAcceleration = 1;
      frontPivotConfig.Feedback.SensorToMechanismRatio = 1 / 1;
      frontPivotConfig.MotorOutput.Inverted = InvertedValue.Clockwise_Positive;
      frontPivotConfig.MotorOutput.NeutralMode = NeutralModeValue.Brake;
      frontPivotConfig.SoftwareLimitSwitch.ForwardSoftLimitEnable = true;
      frontPivotConfig.SoftwareLimitSwitch.ReverseSoftLimitEnable = true;
      frontPivotConfig.SoftwareLimitSwitch.ForwardSoftLimitThreshold = 1;
      frontPivotConfig.SoftwareLimitSwitch.ReverseSoftLimitThreshold = -1;
      frontPivotConfig.ClosedLoopGeneral.ContinuousWrap = false;
      mMasterPivotMotor.getConfigurator().apply(frontPivotConfig);
      mFollowerPivotMotor.getConfigurator().apply(frontPivotConfig);
  }

  /** 
   * 
   * @param d
   * @param h
   * @return
   */
  private static double sampleVelocity(double d, double h) {
    double velocity = Math.sqrt(
      Constants.Hood.G * (Math.sqrt(d * d + h * h) + h)) // the minimum line. go below this velocity and we will hit the SIDE.
        + Math.pow(Math.E, -2 * d) + (d / 3) + 1; // the offset line, adjust as desired
        
    return velocity;
  }

  /** 
  * 
  * @param v The velocity as the piece exits the robot's shooter.
  * @param d The distance from the exit point to the target.
  * @param h The height from the exit point to the target.
  * @return angle in degrees that the hood should aim at in relative to the horizontal plane.
  */
  public static double calculateHoodAngle(double v, double d, double h) {
    final double g = Constants.Hood.G;
    double v2 = v * v;
    double v4 = v * v * v * v;
    double d2 = d * d;
    
        double discriminant = v4 - g * (g * d2 + 2.0 * h * v2);
        if (discriminant < 0.0 || d == 0.0) {
            return Double.NaN; //No physical solution
        }
      double numerator = v2 + Math.sqrt(discriminant);
      double denominator = g * d;
      double angleRadians = Math.atan(numerator / denominator);
      double o = Math.toDegrees(angleRadians);
    return Constants.Hood.THETA_ANGLE_FROM_SHOOTER - o;
  } 

  /** Is the mirror double to the algorithm above but just in launch, not a hood.
  * 
  * @param v The velocity as the piece exits the robot's shooter.
  * @param d The distance from the exit point to the target.
  * @param h The height from the exit point to the target.
  * @return angle in Rad that the particle will launch from relative to the horizontal plane.
  */
  public static double calculateLaunchAngleRad(double v, double d, double h) {
    final double g = Constants.Hood.G;
    double v2 = v * v;
    double v4 = v * v * v * v;
    double d2 = d * d;
    
        double discriminant = v4 - g * (g * d2 + 2.0 * h * v2);
        if (discriminant < 0.0 || d == 0.0) {
            return Double.NaN; //No physical solution
        }
      double numerator = v2 + Math.sqrt(discriminant);
      double denominator = g * d;
      double angleRadians = Math.atan(numerator / denominator);
    return angleRadians;
  } 

  /**
  * Offsets the target position along the line from the robot to the target.
  *
  * This is used to intentionally aim *behind* the hub's center rather than directly at
  * its center. By shifting the target point backward along the robot-to-hub
  * bearing, the shot contacts the back of the hub at a slight angle instead of
  * squaring up in the middle. This promotes more consistent backspin interaction
  * with the hub and improves shot forgiveness and accuracy.
  *
  * A positive transformation distance moves the target farther away from the
  * robot (past the hub), while a negative value pulls the aim point closer.
  *
  * @param currPose Current robot pose on the field
  * @param targetPose Original target position (hub center)
  * @param transformationInMeters Distance to shift the target along the bearing
  * @return Transformed target translation used for aiming
  */
  public static Translation2d transformTarget(Pose2d currPose, Translation2d targetPose, double transformationInMeters) {
    Translation2d deltaTranslation = targetPose.minus(currPose.getTranslation());
    double radAngle = Math.atan2(deltaTranslation.getY(), deltaTranslation.getX());
    return new Translation2d(targetPose.getX() + transformationInMeters * Math.cos(radAngle), targetPose.getY() + transformationInMeters * Math.sin(radAngle));
  }

  // reminder that this is field relative, not robot relative like the actual turret must be.
  public static void simulateTurretAngle(Pose2d currPose, 
                                         Translation2d targetPose, 
                                         double robotFieldYaw,
                                         double robotYawRate,
                                         ChassisSpeeds fieldRobotSpeeds) 
  {
    Translation2d transformedTarget = transformTarget(currPose, targetPose, 0.25);

    double dx = transformedTarget.getX() - currPose.getX();
    double dy = transformedTarget.getY() - currPose.getY();
    double r2 = dx * dx + dy * dy;
    double r = Math.sqrt(r2);
    Logger.recordOutput("Pre-emptive Distance to Goal", r);

    double preliminaryV = sampleVelocity(r, Constants.Hood.HEIGHT_FROM_BOT_TO_TARGET);
    Logger.recordOutput("Pre-emptive Estimated Velocity", preliminaryV);

    double preliminaryTheta = calculateLaunchAngleRad(preliminaryV, r, Constants.Hood.HEIGHT_FROM_BOT_TO_TARGET);
    Logger.recordOutput("Pre-emptive Estimated Launch Angle", Math.toDegrees(preliminaryTheta));

    double timeOFlight = Math.sqrt(r2) / (preliminaryV);

    // This is a tuning line in order to avoid weird behaviors with the estimation line due to inecomplete estimations.
    timeOFlight *= Constants.Hood.TIME_OF_FLIGHT_SCALE; 

    Logger.recordOutput("Pre-emptive Estimated TOF", timeOFlight);

    double x = fieldRobotSpeeds.vxMetersPerSecond;
    double y = fieldRobotSpeeds.vyMetersPerSecond;

    Translation2d imaginaryTarget = transformedTarget.minus(new Translation2d(x, y).times(timeOFlight));
    Pose3d FAKEPOSE = new Pose3d(new Translation3d(imaginaryTarget).plus(new Translation3d(0, 0, Constants.Hood.HEIGHT_FROM_BOT_TO_TARGET)), new Rotation3d());
    
    Logger.recordOutput("Fake Target", FAKEPOSE);

    SimulationObjects.desiredTurretAngleFieldRel = Math.atan2(dy, dx) - robotFieldYaw;
    Logger.recordOutput("Turret 3D Pose", new Pose3d(0, 0, 0, new Rotation3d(0 , 0, SimulationObjects.desiredTurretAngleFieldRel)));
  }
}